### ISSUE TITLE
Julieta: servant/domestic

### ISSUE THREAD

**Issue by orkit** [orkit/Maprom#11]
5.	I need you advice in the following matter. Sometimes a person has a servant/domestic. We have provided the following attribute: servant: yes/no. If I chose “yes”, I may need to input the name and situation of the servant, who most of the times is a Gypsy, hence it is very important to be recorded. Well, actually this servant or servants live (sometimes with their family, i.e. wife, children etc) in the same house with his/her master. Should we record it as co-resident? And have a different category of co-residents. So far, we only have co-residents who are relatives. This can be done very simple, from the menu, where I will specify the type of relation between the co-resident and head of the house. Of course, this issue under no. 5 is not urgent. We may discuss it together later.

**Comment by orkit** [comment]
This could be interesting in the analysis but I think it is a question for David to answer. If yes I can add the structure to the system. Approximately 1-2 weeks to implement.

**Comment by Mriduladevi** [comment]
I gave a thought, and the best way is to make one more category to the co-resident: relative type: SERVANT.

**Comment by orkit** [comment]
Alright, thats a clever way of solving this issue. I will add this.
