### ISSUE TITLE
name of village missing

### ISSUE THREAD

**Issue by Mriduladevi** [orkit/Maprom#29]
For the newly 3 sub/districts input, Gherghița, Amaradia and Dâmbovița Plai, the name of the village is missing in the Village menu. Please check taht for instance I have modified/edited the village Pe Lacuri from Gherghița subdistrict, and still, the name persist as it was entered long ago, before you worked some update or so. Can I also have these villages arranged in alphabetic order, according to Romanian alphabet. i never know where ă, î, â, ț and ș will follow. If not, leave it in English order, but right now it is a combination of both. :)

**Comment by orkit** [comment]
In the new update the arranging of Village names can be done in the table head.
